# Welcome to the code of Turtle Text!
# yes, it's ugly, and probably hugely
# inefficient, but hey, it works!
# i know it's quite hard to change the
# lettering, but hey, that's my code

# imports
import turtle
# variables
turtles = [[turtle.Turtle(), -245, -50], [turtle.Turtle(), -190, -50], [turtle.Turtle(), -135, -50], [turtle.Turtle(), -80, -50], [turtle.Turtle(), -25, -50], [turtle.Turtle(), 30, -50], [turtle.Turtle(), 85, -50], [turtle.Turtle(), 150, -50], [turtle.Turtle(), 215, -50]]
screen = turtle.Screen()
# functions
def turtlesetup(turtleinfo):
    turtleinfo[0].pensize(5)
    turtleinfo[0].penup()
    turtleinfo[0].goto(turtleinfo[1], turtleinfo[2])
    turtleinfo[0].left(90)
def a(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(100)
    turtle.penup()
    turtle.back(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.goto(goto1, goto2)


def b(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.penup()
    turtle.forward(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.goto(goto1, goto2)
    turtle.left(90)


def c(turtle):
    goto1, goto2 = turtle.pos()
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.goto(goto1, goto2)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.goto(goto1, goto2)


def d(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.penup()
    turtle.goto(goto1, goto2)

def e(turtle):
    goto1, goto2 = turtle.pos()
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.goto(goto1, goto2)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.back(45)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.goto(goto1, goto2)


def f(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.forward(100)
    turtle.back(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.goto(goto1, goto2)    

def g(turtle):
    goto1, goto2 = turtle.pos()
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.penup()
    turtle.right(90)
    turtle.goto(goto1, goto2)
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.goto(goto1, goto2)


def h(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.penup()
    turtle.forward(45)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.penup()
    turtle.back(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.goto(goto1, goto2)
def i(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.right(90)
    turtle.forward(45)
    turtle.penup()
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.back(22.5)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.penup()
    turtle.right(180)
    turtle.goto(goto1, goto2)
# setup
# screen setup
screen.setup(1280, 720)
# turtle setup
for turtleinfo in turtles:
    turtlesetup(turtleinfo)
# make the turtles display letters (currently used to test lettering)
a(turtles[0][0])
b(turtles[1][0])
c(turtles[2][0])
d(turtles[3][0])
e(turtles[4][0])
f(turtles[5][0])
g(turtles[6][0])
h(turtles[7][0])
i(turtles[8][0])
