# Welcome to the code of Turtle Text!
# yes, it's ugly, and probably hugely
# inefficient, but hey, it works!
# i know it's quite hard to change the
# lettering, but hey, that's my code

# imports
import turtle
# setup of turtles and screen (should probably be cleaned up at some point)
# creation
t1 = turtle.Turtle()
t2 = turtle.Turtle()
t3 = turtle.Turtle()
t4 = turtle.Turtle()
t5 = turtle.Turtle()
t6 = turtle.Turtle()
t7 = turtle.Turtle()
t8 = turtle.Turtle()
t9 = turtle.Turtle()
# thicker text
t1.pensize(5)
t2.pensize(5)
t3.pensize(5)
t4.pensize(5)
t5.pensize(5)
t6.pensize(5)
t7.pensize(5)
t8.pensize(5)
t9.pensize(5)
# makes the screen
screen = turtle.Screen()
screen.setup(1280, 720)
# don't draw lines when moving
t1.penup()
t2.penup()
t3.penup()
t4.penup()
t5.penup()
t6.penup()
t7.penup()
t8.penup()
t9.penup()
# move to the right position
t1.goto(-245, -50)
t2.goto(-190, -50)
t3.goto(-135, -50)
t4.goto(-80, -50)
t5.goto(-25, -50)
t6.goto(30, -50)
t7.goto(85, -50)
t8.goto(140, -50)
t9.goto(195, -50)
# face up
t1.left(90)
t2.left(90)
t3.left(90)
t4.left(90)
t5.left(90)
t6.left(90)
t7.left(90)
t8.left(90)
t9.left(90)

# letter functions
# i create these in whatever way I do, they will not be very organised
def a(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(100)
    turtle.penup()
    turtle.back(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.goto(goto1, goto2)


def b(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.penup()
    turtle.forward(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.goto(goto1, goto2)
    turtle.left(90)


def c(turtle):
    goto1, goto2 = turtle.pos()
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.goto(goto1, goto2)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.goto(goto1, goto2)


def d(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.penup()
    turtle.goto(goto1, goto2)

def e(turtle):
    goto1, goto2 = turtle.pos()
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.goto(goto1, goto2)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.penup()
    turtle.back(45)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.goto(goto1, goto2)


def f(turtle):
    goto1, goto2 = turtle.pos()
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.forward(100)
    turtle.back(50)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.right(90)
    turtle.penup()
    turtle.goto(goto1, goto2)    

def g(turtle):
    goto1, goto2 = turtle.pos()
    turtle.right(90)
    turtle.pendown()
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.penup()
    turtle.right(90)
    turtle.goto(goto1, goto2)
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(90)
    turtle.penup()
    turtle.goto(goto1, goto2)
# make the turtles display letters (currently used to test lettering)
a(t1)
b(t2)
c(t3)
d(t4)
e(t5)
f(t6)
g(t7)
a(t8)
b(t9)
